// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionButtons: typeof import('./src/components/ActionButtons.vue')['default']
    AttributeButtons: typeof import('./src/components/AttributeButtons.vue')['default']
    ColorCarousel: typeof import('./src/components/ColorCarousel.vue')['default']
    ConfirmClearDialog: typeof import('./src/components/ConfirmClearDialog.vue')['default']
    FeatherAppBar: typeof import('@featherds/app-bar')['FeatherAppBar']
    FeatherAppBarLink: typeof import('@featherds/app-bar')['FeatherAppBarLink']
    FeatherAppLayout: typeof import('@featherds/app-layout')['FeatherAppLayout']
    FeatherButton: typeof import('@featherds/button')['FeatherButton']
    FeatherDialog: typeof import('@featherds/dialog')['FeatherDialog']
    FeatherIcon: typeof import('@featherds/icon')['FeatherIcon']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KiwiContainer: typeof import('./src/components/KiwiContainer.vue')['default']
    LogoPicker: typeof import('./src/components/LogoPicker.vue')['default']
    Menubar: typeof import('./src/components/Menubar.vue')['default']
    ObjectsCarousel: typeof import('./src/components/ObjectsCarousel.vue')['default']
  }
}
